[relaychain]
default_command = "../polkadot/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "kusama-local"

	[[relaychain.nodes]]
	name = "alice"
	validator = true

	[[relaychain.nodes]]
	name = "bob"
	validator = true

	[[relaychain.nodes]]
	name = "charlie"
	validator = true

	[[relaychain.nodes]]
	name = "dave"
	validator = true

[[parachains]]
id = 1003
chain = "bridge-hub-kusama-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/release/polkadot-parachain"
	args = ["-lparachain=debug"]

	# run bob as parachain collator
	[[parachains.collators]]
	name = "bob"
	validator = true
	command = "./target/release/polkadot-parachain"
	args = ["-lparachain=debug"]


[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "statemine-local"

[[parachains.collators]]
name = "statemine-collator01"
command = "./target/release/polkadot-parachain"
args = ["--log=xcm=trace"]

[[parachains.collators]]
name = "statemine-collator02"
command = "./target/release/polkadot-parachain"
args = ["--log=xcm=trace"]

[[hrmp_channels]]
sender = 1003
recipient = 1000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 1000
recipient = 1003
max_capacity = 8
max_message_size = 512
